### ISSUE TITLE
Problems binding keys on function layer

### ISSUE THREAD

**Issue by hungsu** [kprinssu/anne-keyboard-windows#21]
Hi, I've noticed a few problems with using the Windows 10 app to bind things to the Function layer

![](http://i.imgur.com/oWg6B8Y.png)

With this layout:
The fourth row is shifted to the left one key, so Fn+Shift is ".", Fn+Z is "," and so on
Binding Fn+Spacebar actually binds Fn+LeftCtrl. So in this case, pressing Function+LeftCtrl is Enter

Any idea what I can do?

**Comment by kprinssu** [comment]
It was a bug that was recently fixed in https://github.com/kprinssu/anne-keyboard-windows/commit/81db9ef09ad2d11ad04b1f760298adaf6d447880

Unfortunately, I do not have a new build or access to a windows machine until the end of the month. You need to clone the project, build, and manually install it.

**Comment by kprinssu** [comment]
Your issue should be fixed in https://github.com/kprinssu/anne-keyboard-windows/releases/tag/1.0.3

Please let me know if you have the same issue.
